[Variables]

skinSize=900
lastSetWidth=900

Player=Spotify
alignRight=0

activePlugin=NowPlaying

topTextWidth=0
bottomTextWidth=0

; 0 = MUSIC, 2 = WEBNOWPLAYING
MusicSwitch=0
playerController=Title0
currentlySetName=Spotify (NowPlaying)
currentlySetPlayer=WMP

adaptiveHideActive=0

stowAway=0
stowAwayName=NULL

topText=mArtist
bottomText=mTitle

disableScroll=0

removeExtraFromText=0

thinFont=Metropolis Extra Light
thickFont=Metropolis Medium
controlsFont=Metropolis Medium

mediaTextPositionHor=0
mediaTextAlignment=LeftBottom
mediaTextAlignmentPure=Left
interfaceTextAlignment=Right
nowTextPositionHor=166.5
hairlinePositionHor=193.5
topTextPositionHor=222.75
playCtrlPositionHor=90
settingsTextPositionHor=103.5
indicatorPositionHor=63
indicatorPositionHorPure=36
conflictIndicatorPositionHor=27
conflictIndicatorPositionHorPure=72
