[0]
Meter=String
MeterStyle=s
Text=Input
LeftMouseDownAction=[!SetVariable AudioDevicePort "Input" "#ROOTCONFIG#\SettingsWindow"][!WriteKeyValue Variables AudioDevicePort "Input" "C:\Users\SC21B074-Abhishek202\Documents\Rainmeter\Skins\VisBubble\Settings.inc"][!SetOption AudioDevicePort_Select Text "Input" "#ROOTCONFIG#\SettingsWindow"][!Refresh "#ROOTCONFIG#\SettingsWindow"][!DeactivateConfig]
[1]
Meter=String
MeterStyle=s
Text=Output
LeftMouseDownAction=[!SetVariable AudioDevicePort "Output" "#ROOTCONFIG#\SettingsWindow"][!WriteKeyValue Variables AudioDevicePort "Output" "C:\Users\SC21B074-Abhishek202\Documents\Rainmeter\Skins\VisBubble\Settings.inc"][!SetOption AudioDevicePort_Select Text "Output" "#ROOTCONFIG#\SettingsWindow"][!Refresh "#ROOTCONFIG#\SettingsWindow"][!DeactivateConfig]
